import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Laurie",
      email: "lauriewaller7@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "Sapphire",
      email: "Sapphire@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      _id: "1",
      name: "Lululemon Leggings",
      category: "Leggings",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 0,
      brand: "Lululemon",
      rating: 4.5,
      numReviews: 10,
      description: "Let's face it — we can't live without them",
    },
    {
      _id: "2",
      name: "Adidas Fit Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 100,
      countInStock: 100,
      brand: "Adidas",
      rating: 3.0,
      numReviews: 10,
      description: "You've never been more fit",
    },
    {
      _id: "3",
      name: "Lacoste Free Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 220,
      countInStock: 10,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "For when you need an escape",
    },
    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 78,
      countInStock: 25,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "The best slimming pants in the biz",
    },
    {
      _id: "5",
      name: "Puma Slim Pant",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 65,
      countInStock: 10,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "For when you want to feel skinny",
    },
    {
      _id: "6",
      name: "Adidas Fit Pant",
      category: "Pants",
      image: "/images/p1.jpg",
      price: 139,
      countInStock: 100,
      brand: "Adidas",
      rating: 2.0,
      numReviews: 15,
      description: "These will get you by",
    },
  ],
};
export default data;
